GMaster.TalentDB = {
["Warlock"] = {
								{ 
									["name"] = "Affliction", 
									["data"] = {
														
															{ "Doom and Gloom", "Interface\\Icons\\Spell_Shadow_CurseOfSargeras", 1, 1},
															{ "Improved Life Tap", "Interface\\Icons\\Spell_Shadow_BurningSpirit", 1, 2},
															{ "Improved Corruption", "Interface\\Icons\\Spell_Shadow_AbominationExplosion", 1, 3},
															{ "Jinx", "INTERFACE\\ICONS\\ability_warlock_jinx", 2, 1},
															{ "Soul Siphon", "INTERFACE\\ICONS\\ability_warlock_soulsiphon", 2, 2},
															{ "Siphon Life", "Interface\\Icons\\Spell_Shadow_Requiem", 2, 3},
															{ "Curse of Exhaustion", "Interface\\Icons\\Spell_Shadow_GrimWard", 3, 1},
															{ "Improved Fear", "Interface\\Icons\\Spell_Shadow_Possession", 3, 3},
															{ "Eradication", "Interface\\Icons\\Ability_Warlock_Eradication", 3, 4},
															{ "Improved Howl of Terror", "Interface\\Icons\\Spell_Shadow_DeathScream", 4, 1},
															{ "Soul Swap", "INTERFACE\\ICONS\\ability_warlock_soulswap", 4, 2},
															{ "Shadow Embrace", "Interface\\Icons\\Spell_Shadow_ShadowEmbrace", 4, 3},
															{ "Death's Embrace", "Interface\\Icons\\Spell_Shadow_DeathsEmbrace", 5, 1},
															{ "Nightfall", "Interface\\Icons\\Spell_Shadow_Twilight", 5, 2},
															{ "Soulburn: Seed of Corruption", "Interface\\Icons\\Spell_Shadow_SeedOfDestruction", 5, 3},
															{ "Everlasting Affliction", "Interface\\Icons\\Ability_Warlock_EverlastingAffliction", 6, 2},
															{ "Pandemic", "INTERFACE\\ICONS\\spell_shadow_lastingaffliction", 6, 3},
															{ "Haunt", "Interface\\Icons\\Ability_Warlock_Haunt", 7, 2},
														},
								},
								{
									["name"] = "Demonology", 
									["data"] = {
															{ "Demonic Embrace", "Interface\\Icons\\Spell_Shadow_Metamorphosis", 1, 1},
															{ "Dark Arts", "INTERFACE\\ICONS\\ability_warlock_darkarts", 1, 2},
															{ "Fel Synergy", "Interface\\Icons\\Spell_Shadow_FelMending", 1, 3},
															{ "Demonic Rebirth", "Interface\\Icons\\Spell_Shadow_DemonicTactics", 2, 1},
															{ "Mana Feed", "Interface\\Icons\\Spell_Shadow_ManaFeed", 2, 2},
															{ "Demonic Aegis", "Interface\\Icons\\Spell_Shadow_RagingScream", 2, 3},
															{ "Master Summoner", "Interface\\Icons\\Spell_Shadow_ImpPhaseShift", 2, 4},
															{ "Impending Doom", "Interface\\Icons\\Spell_Nature_RemoveCurse", 3, 1},
															{ "Demonic Empowerment", "Interface\\Icons\\Ability_Warlock_DemonicEmpowerment", 3, 2},
															{ "Improved Health Funnel", "Interface\\Icons\\Spell_Shadow_LifeDrain", 3, 3},
															{ "Molten Core", "Interface\\Icons\\Ability_Warlock_MoltenCore", 4, 1},
															{ "Hand of Gul'dan", "Interface\\Icons\\INV_SummerFest_FireSpirit", 4, 2},
															{ "Aura of Foreboding", "Interface\\Icons\\Spell_Shadow_SealOfKings", 4, 3},
															{ "Ancient Grimoire", "INTERFACE\\ICONS\\ability_warlock_ancientgrimoire", 5, 1},
															{ "Inferno", "INTERFACE\\ICONS\\ability_warlock_inferno", 5, 2},
															{ "Decimation", "Interface\\Icons\\Spell_Fire_Fireball02", 5, 3},
															{ "Cremation", "INTERFACE\\ICONS\\ability_warlock_cremation", 6, 2},
															{ "Demonic Pact", "Interface\\Icons\\Spell_Shadow_DemonicPact", 6, 3},
															{ "Metamorphosis", "Interface\\Icons\\Spell_Shadow_DemonForm", 7, 2},
															},
								},
								{ 
									["name"] = "Destruction", 
									["data"] = {
															{ "Bane", "Interface\\Icons\\Spell_Shadow_DeathPact", 1, 1},
															{ "Shadow and Flame", "Interface\\Icons\\Spell_Shadow_ShadowandFlame", 1, 2},
															{ "Improved Immolate", "Interface\\Icons\\Spell_Fire_Immolation", 1, 3},
															{ "Aftermath", "Interface\\Icons\\Spell_Fire_Fire", 2, 1},
															{ "Emberstorm", "Interface\\Icons\\Spell_Fire_SelfDestruct", 2, 2},
															{ "Improved Searing Pain", "Interface\\Icons\\Spell_Fire_SoulBurn", 2, 3},
															{ "Improved Soul Fire", "Interface\\Icons\\Spell_Fire_Fireball02", 3, 1},
															{ "Backdraft", "Interface\\Icons\\Ability_Warlock_Backdraft", 3, 2},
															{ "Shadowburn", "Interface\\Icons\\Spell_Shadow_ScourgeBuild", 3, 3},
															{ "Burning Embers", "INTERFACE\\ICONS\\ability_warlock_burningembers", 4, 1},
															{ "Soul Leech", "Interface\\Icons\\Spell_Shadow_SoulLeech_3", 4, 2},
															{ "Backlash", "Interface\\Icons\\Spell_Fire_PlayingWithFire", 4, 3},
															{ "Nether Ward", "Interface\\Icons\\Spell_Fire_FelFireward", 4, 4},
															{ "Fire and Brimstone", "Interface\\Icons\\Ability_Warlock_FireandBrimstone", 5, 2},
															{ "Shadowfury", "Interface\\Icons\\Spell_Shadow_Shadowfury", 5, 3},
															{ "Nether Protection", "Interface\\Icons\\Spell_Shadow_NetherProtection", 5, 4},
															{ "Empowered Imp", "Interface\\Icons\\Ability_Warlock_EmpoweredImp", 6, 1},
															{ "Bane of Havoc", "INTERFACE\\ICONS\\ability_warlock_baneofhavoc", 6, 3},
															{ "Chaos Bolt", "Interface\\Icons\\Ability_Warlock_ChaosBolt", 7, 2},
															}
								}
		},
								
["Rogue"] = {
							{
								["name"] = "Assassination", 
								["data"] = {	
															{ "Deadly Momentum", "INTERFACE\\ICONS\\ability_rogue_deadlymomentum", 1, 1},
															{ "Coup de Grace", "Interface\\Icons\\Ability_Rogue_Eviscerate", 1, 2},
															{ "Lethality", "Interface\\Icons\\Ability_CriticalStrike", 1, 3},
															{ "Ruthlessness", "Interface\\Icons\\Ability_Druid_Disembowel", 2, 1},
															{ "Quickening", "Interface\\Icons\\Ability_Rogue_QuickRecovery", 2, 2},
															{ "Puncturing Wounds", "Interface\\Icons\\Ability_BackStab", 2, 3},
															{ "Blackjack", "INTERFACE\\ICONS\\ability_rogue_blackjack", 2, 4},
															{ "Deadly Brew", "Interface\\Icons\\Ability_Rogue_DeadlyBrew", 3, 1},
															{ "Cold Blood", "Interface\\Icons\\Spell_Ice_Lament", 3, 2},
															{ "Vile Poisons", "Interface\\Icons\\Ability_Rogue_FeignDeath", 3, 3},
															{ "Deadened Nerves", "Interface\\Icons\\Ability_Rogue_DeadenedNerves", 4, 1},
															{ "Seal Fate", "Interface\\Icons\\Ability_Rogue_StayofExecution", 4, 2},
															{ "Murderous Intent", "Interface\\Icons\\Spell_Shadow_DeathScream", 5, 1},
															{ "Overkill", "Interface\\Icons\\Ability_Hunter_RapidKilling", 5, 2},
															{ "Master Poisoner", "Interface\\Icons\\Ability_Creature_Poison_06", 5, 3},
															{ "Improved Expose Armor", "Interface\\Icons\\Ability_Warrior_Riposte", 5, 4},
															{ "Cut to the Chase", "Interface\\Icons\\Ability_Rogue_CutToTheChase", 6, 2},
															{ "Venomous Wounds", "INTERFACE\\ICONS\\ability_rogue_venomouswounds", 6, 3},
															{ "Vendetta", "INTERFACE\\ICONS\\ability_rogue_deadliness", 7, 2},
														},
							},
							{ 
								["name"] = "Combat", 
								["data"] = {
															{ "Improved Recuperate", "INTERFACE\\ICONS\\ability_rogue_improvedrecuperate", 1, 1},
															{ "Improved Sinister Strike", "Interface\\Icons\\Spell_Shadow_RitualOfSacrifice", 1, 2},
															{ "Precision", "Interface\\Icons\\Ability_Marksmanship", 1, 3},
															{ "Improved Slice and Dice", "Interface\\Icons\\Ability_Rogue_SliceDice", 2, 1},
															{ "Improved Sprint", "Interface\\Icons\\Ability_Rogue_Sprint", 2, 2},
															{ "Aggression", "Interface\\Icons\\Ability_Racial_Avatar", 2, 3},
															{ "Improved Kick", "Interface\\Icons\\Ability_Kick", 2, 4},
															{ "Lightning Reflexes", "Interface\\Icons\\Spell_Nature_Invisibilty", 3, 1},
															{ "Revealing Strike", "INTERFACE\\ICONS\\inv_sword_97", 3, 2},
															{ "Reinforced Leather", "INTERFACE\\ICONS\\ability_rogue_reinforcedleather", 3, 3},
															{ "Improved Gouge", "Interface\\Icons\\Ability_Gouge", 3, 4},
															{ "Combat Potency", "Interface\\Icons\\INV_Weapon_Shortblade_38", 4, 2},
															{ "Blade Twisting", "Interface\\Icons\\Ability_Rogue_BladeTwisting", 4, 3},
															{ "Throwing Specialization", "Interface\\Icons\\Ability_Rogue_ThrowingSpecialization", 5, 1},
															{ "Adrenaline Rush", "Interface\\Icons\\Spell_Shadow_ShadowWordDominate", 5, 2},
															{ "Savage Combat", "Interface\\Icons\\Ability_Creature_Disease_03", 5, 3},
															{ "Bandit's Guile", "Interface\\Icons\\Ability_Rogue_PreyontheWeak", 6, 1},
															{ "Restless Blades", "INTERFACE\\ICONS\\ability_rogue_restlessblades", 6, 3},
															{ "Killing Spree", "Interface\\Icons\\Ability_Rogue_MurderSpree", 7, 2},
														}
							},
							{
								["name"] = "Subtlety", 
								["data"] = {
															{ "Nightstalker", "Interface\\Icons\\Ability_Stealth", 1, 1},
															{ "Improved Ambush", "Interface\\Icons\\Ability_Rogue_Ambush", 1, 2},
															{ "Relentless Strikes", "Interface\\Icons\\Ability_Warrior_DecisiveStrike", 1, 3},
															{ "Elusiveness", "Interface\\Icons\\Spell_Magic_LesserInvisibilty", 2, 1},
															{ "Waylay", "Interface\\Icons\\Ability_Rogue_Waylay", 2, 2},
															{ "Opportunity", "Interface\\Icons\\Ability_Rogue_BloodSplatter", 2, 3},
															{ "Initiative", "Interface\\Icons\\Spell_Shadow_Fumble", 2, 4},
															{ "Energetic Recovery", "INTERFACE\\ICONS\\ability_rogue_sturdyrecuperate", 3, 1},
															{ "Find Weakness", "Interface\\Icons\\Ability_Rogue_FindWeakness", 3, 2},
															{ "Hemorrhage", "Interface\\Icons\\Spell_Shadow_LifeDrain", 3, 3},
															{ "Honor Among Thieves", "Interface\\Icons\\Ability_Rogue_HonorAmongstThieves", 4, 1},
															{ "Premeditation", "Interface\\Icons\\Spell_Shadow_Possession", 4, 2},
															{ "Enveloping Shadows", "Interface\\Icons\\Ability_Rogue_EnvelopingShadows", 4, 4},
															{ "Cheat Death", "Interface\\Icons\\Ability_Rogue_CheatDeath", 5, 1},
															{ "Preparation", "INTERFACE\\ICONS\\ability_rogue_preparation", 5, 2},
															{ "Sanguinary Vein", "INTERFACE\\ICONS\\ability_rogue_sanguinaryvein", 5, 3},
															{ "Slaughter from the Shadows", "Interface\\Icons\\Ability_Rogue_SlaughterfromtheShadows", 6, 2},
															{ "Serrated Blades", "Interface\\Icons\\INV_Sword_17", 6, 3},
															{ "Shadow Dance", "Interface\\Icons\\Ability_Rogue_ShadowDance", 7, 2},
														}
							}
						},

["Druid"] = {
							{ 
								["name"] = "Balance", 
								["data"] = {
														{ "Nature's Grace", "Interface\\Icons\\Spell_Nature_NaturesBlessing", 1, 1},
														{ "Starlight Wrath", "Interface\\Icons\\Spell_Nature_AbolishMagic", 1, 2},
														{ "Nature's Majesty", "Interface\\Icons\\INV_Staff_01", 1, 3},
														{ "Genesis", "Interface\\Icons\\Spell_Arcane_Arcane03", 2, 1},
														{ "Moonglow", "Interface\\Icons\\Spell_Nature_Sentinal", 2, 2},
														{ "Balance of Power", "Interface\\Icons\\Ability_Druid_BalanceofPower", 2, 3},
														{ "Euphoria", "INTERFACE\\ICONS\\achievement_boss_valithradreamwalker", 3, 1},
														{ "Moonkin Form", "Interface\\Icons\\Spell_Nature_ForceOfNature", 3, 2},
														{ "Typhoon", "Interface\\Icons\\Ability_Druid_Typhoon", 3, 3},
														{ "Shooting Stars", "Interface\\Icons\\Ability_Mage_ArcaneBarrage", 3, 4},
														{ "Owlkin Frenzy", "Interface\\Icons\\Ability_Druid_OwlkinFrenzy", 4, 2},
														{ "Gale Winds", "Interface\\Icons\\Ability_Druid_GaleWinds", 4, 3},
														{ "Solar Beam", "Interface\\Icons\\ability_vehicle_sonicshockwave", 4, 4},
														{ "Dreamstate", "Interface\\Icons\\Ability_Druid_Dreamstate", 5, 1},
														{ "Force of Nature", "Interface\\Icons\\Ability_Druid_ForceofNature", 5, 2},
														{ "Sunfire", "Interface\\Icons\\Ability_Mage_FireStarter", 5, 3},
														{ "Earth and Moon", "Interface\\Icons\\Ability_Druid_EarthandSky", 5, 4},
														{ "Fungal Growth", "Interface\\Icons\\Creature_SporeMushroom", 6, 2},
														{ "Lunar Shower", "Interface\\Icons\\Achievement_WorldEvent_Lunar", 6, 3},
														{ "Starfall", "Interface\\Icons\\Ability_Druid_Starfall", 7, 2},
													 },
							},
							{
								["name"] = "Feral Combat", 
								["data"] = {
														{ "Feral Swiftness", "Interface\\Icons\\Spell_Nature_SpiritWolf", 1, 1},
														{ "Furor", "Interface\\Icons\\Spell_Holy_BlessingOfStamina", 1, 2},
														{ "Predatory Strikes", "Interface\\Icons\\Ability_Hunter_Pet_Cat", 1, 3},
														{ "Infected Wounds", "Interface\\Icons\\Ability_Druid_InfectedWound", 2, 1},
														{ "Fury Swipes", "Interface\\Icons\\Ability_Druid_Mangle.tga", 2, 2},
														{ "Primal Fury", "Interface\\Icons\\Ability_Racial_Cannibalize", 2, 3},
														{ "Feral Aggression", "Interface\\Icons\\Ability_Druid_DemoralizingRoar", 2, 4},
														{ "King of the Jungle", "Interface\\Icons\\Ability_Druid_KingoftheJungle", 3, 1},
														{ "Feral Charge", "Interface\\Icons\\Ability_Hunter_Pet_Bear", 3, 2},
														{ "Stampede", "Interface\\Icons\\spell_druid_feralchargecat", 3, 3},
														{ "Thick Hide", "Interface\\Icons\\INV_Misc_Pelt_Bear_03", 3, 4},
														{ "Leader of the Pack", "Interface\\Icons\\Spell_Nature_UnyeildingStamina", 4, 2},
														{ "Brutal Impact", "Interface\\Icons\\Ability_Druid_Bash", 4, 3},
														{ "Nurturing Instinct", "Interface\\Icons\\Ability_Druid_HealingInstincts", 4, 4},
														{ "Primal Madness", "Interface\\Icons\\Ability_Mount_JungleTiger", 5, 1},
														{ "Survival Instincts", "Interface\\Icons\\Ability_Druid_TigersRoar", 5, 2},
														{ "Endless Carnage", "Interface\\Icons\\Spell_DeathKnight_BloodBoil", 5, 3},
														{ "Natural Reaction", "Interface\\Icons\\Ability_BullRush", 5, 4},
														{ "Blood in the Water", "INTERFACE\\ICONS\\inv_misc_food_134_meat", 6, 1},
														{ "Rend and Tear", "Interface\\Icons\\Ability_Druid_PrimalAgression", 6, 2},
														{ "Pulverize", "Interface\\Icons\\Ability_Smash", 6, 3},
														{ "Berserk", "Interface\\Icons\\Ability_Druid_Berserk", 7, 2},
													 }
							},
							{ 
								["name"] = "Restoration", 
								["data"] = {
														{ "Blessing of the Grove", "Interface\\Icons\\Spell_Shaman_SpiritLink", 1, 1},
														{ "Natural Shapeshifter", "Interface\\Icons\\Spell_Nature_WispSplode", 1, 2},
														{ "Naturalist", "Interface\\Icons\\Spell_Nature_HealingTouch", 1, 3},
														{ "Heart of the Wild", "Interface\\Icons\\Spell_Holy_BlessingOfAgility", 1, 4},
														{ "Perseverance", "Interface\\Icons\\Achievement_Zone_Darnassus", 2, 1},
														{ "Master Shapeshifter", "Interface\\Icons\\Ability_Druid_MasterShapeshifter", 2, 2},
														{ "Improved Rejuvenation", "Interface\\Icons\\Spell_Nature_Rejuvenation", 2, 3},
														{ "Living Seed", "Interface\\Icons\\Ability_Druid_GiftoftheEarthmother", 3, 1},
														{ "Revitalize", "Interface\\Icons\\Ability_Druid_Replenish", 3, 2},
														{ "Nature's Swiftness", "Interface\\Icons\\Spell_Nature_RavenForm", 3, 3},
														{ "Fury of Stormrage", "INTERFACE\\ICONS\\inv_staff_90", 3, 4},
														{ "Nature's Bounty", "Interface\\Icons\\Spell_Nature_ResistNature", 4, 2},
														{ "Empowered Touch", "Interface\\Icons\\Ability_Druid_EmpoweredTouch", 4, 3},
														{ "Malfurion's Gift", "Interface\\Icons\\Spell_Shaman_GiftEarthmother", 4, 4},
														{ "Efflorescence", "Interface\\Icons\\INV_Misc_Herb_TalandrasRose", 5, 1},
														{ "Wild Growth", "Interface\\Icons\\Ability_Druid_Flourish", 5, 2},
														{ "Nature's Cure", "Interface\\Icons\\Ability_Shaman_CleanseSpirit", 5, 3},
														{ "Nature's Ward", "Interface\\Icons\\Ability_Druid_NaturalPerfection", 5, 4},
														{ "Gift of the Earthmother", "Interface\\Icons\\Ability_Druid_ManaTree", 6, 1},
														{ "Swift Rejuvenation", "Interface\\Icons\\Ability_Druid_EmpoweredRejuvination", 6, 3},
														{ "Tree of Life", "Interface\\Icons\\Ability_Druid_TreeofLife", 7, 2},
												   }
							}
			},

["Hunter"] = {
							{ 
								["name"] = "Beast Mastery", 
								["data"] = {
														{ "Improved Kill Command", "Interface\\Icons\\Ability_Hunter_SilentHunter", 1, 1},
														{ "One with Nature", "INTERFACE\\ICONS\\ability_hunter_onewithnature", 1, 2},
														{ "Bestial Discipline", "INTERFACE\\ICONS\\ability_hunter_bestialdiscipline", 1, 3},
														{ "Pathfinding", "INTERFACE\\ICONS\\ability_hunter_pathfinding2", 2, 1},
														{ "Spirit Bond", "Interface\\Icons\\Ability_Druid_DemoralizingRoar", 2, 2},
														{ "Frenzy", "Interface\\Icons\\INV_Misc_MonsterClaw_03", 2, 3},
														{ "Improved Mend Pet", "Interface\\Icons\\Ability_Hunter_MendPet", 2, 4},
														{ "Cobra Strikes", "Interface\\Icons\\Ability_Hunter_CobraStrikes", 3, 1},
														{ "Fervor", "Interface\\Icons\\Ability_Hunter_AspectoftheViper", 3, 2},
														{ "Focus Fire", "INTERFACE\\ICONS\\ability_hunter_focusfire", 3, 3},
														{ "Longevity", "Interface\\Icons\\Ability_Hunter_Longevity", 4, 1},
														{ "Killing Streak", "INTERFACE\\ICONS\\achievement_bg_kill_carrier_opposing_flagroom", 4, 3},
														{ "Crouching Tiger, Hidden Chimera", "INTERFACE\\ICONS\\ability_hunter_pet_chimera", 5, 1},
														{ "Bestial Wrath", "Interface\\Icons\\Ability_Druid_FerociousBite", 5, 2},
														{ "Ferocious Inspiration", "Interface\\Icons\\Ability_Hunter_FerociousInspiration", 5, 3},
														{ "Kindred Spirits", "Interface\\Icons\\Ability_Hunter_SeparationAnxiety", 6, 1},
														{ "The Beast Within", "Interface\\Icons\\Ability_Hunter_BeastWithin", 6, 2},
														{ "Invigoration", "Interface\\Icons\\Ability_Hunter_Invigeration", 6, 3},
														{ "Beast Mastery", "Interface\\Icons\\Ability_Hunter_BeastMastery", 7, 2},
													 }
							},
							{ 
								["name"] = "Marksmanship", 
								["data"] = {
														{ "Go for the Throat", "Interface\\Icons\\Ability_Hunter_GoForTheThroat", 1, 1},
														{ "Efficiency", "Interface\\Icons\\Ability_Hunter_FocusedAim", 1, 2},
														{ "Rapid Killing", "Interface\\Icons\\Ability_Hunter_RapidKilling", 1, 3},
														{ "Sic 'Em!", "INTERFACE\\ICONS\\ability_hunter_sickem", 2, 1},
														{ "Improved Steady Shot", "Interface\\Icons\\Ability_Hunter_ImprovedSteadyShot", 2, 2},
														{ "Careful Aim", "Interface\\Icons\\Ability_Hunter_ZenArchery", 2, 3},
														{ "Silencing Shot", "Interface\\Icons\\Ability_TheBlackArrow", 3, 1},
														{ "Concussive Barrage", "INTERFACE\\ICONS\\ability_hunter_efficiency", 3, 2},
														{ "Piercing Shots", "Interface\\Icons\\Ability_Hunter_PiercingShots", 3, 3},
														{ "Bombardment", "Interface\\Icons\\Ability_Marksmanship", 4, 1},
														{ "Trueshot Aura", "Interface\\Icons\\Ability_TrueShot", 4, 2},
														{ "Termination", "Interface\\Icons\\Ability_Warrior_FocusedRage", 4, 3},
														{ "Resistance is Futile", "INTERFACE\\ICONS\\ability_hunter_resistanceisfutile", 4, 4},
														{ "Rapid Recuperation", "Interface\\Icons\\Ability_Hunter_RapidRegeneration", 5, 1},
														{ "Master Marksman", "Interface\\Icons\\Ability_Hunter_MasterMarksman", 5, 2},
														{ "Readiness", "Interface\\Icons\\Ability_Hunter_Readiness", 5, 4},
														{ "Posthaste", "INTERFACE\\ICONS\\ability_hunter_posthaste", 6, 1},
														{ "Marked for Death", "Interface\\Icons\\Ability_Hunter_Assassinate", 6, 3},
														{ "Chimera Shot", "Interface\\Icons\\Ability_Hunter_ChimeraShot2", 7, 2},
													 }
							},
							{
								["name"] = "Survival", 
								["data"] = {
														{ "Hunter vs. Wild", "Interface\\Icons\\Ability_Hunter_HunterVsWild", 1, 1},
														{ "Pathing", "Interface\\Icons\\Ability_Hunter_ImprovedTracking", 1, 2},
														{ "Improved Serpent Sting", "Interface\\Icons\\Ability_Hunter_Quickshot", 1, 3},
														{ "Survival Tactics", "Interface\\Icons\\Ability_Rogue_FeignDeath", 2, 1},
														{ "Trap Mastery", "Interface\\Icons\\Ability_Ensnare", 2, 2},
														{ "Entrapment", "Interface\\Icons\\Spell_Nature_StrangleVines", 2, 3},
														{ "Point of No Escape", "Interface\\Icons\\Ability_Hunter_PointofNoEscape", 2, 4},
														{ "Thrill of the Hunt", "Interface\\Icons\\Ability_Hunter_ThrilloftheHunt", 3, 1},
														{ "Counterattack", "Interface\\Icons\\Ability_Warrior_Challange", 3, 2},
														{ "Lock and Load", "Interface\\Icons\\Ability_Hunter_LockAndLoad", 3, 3},
														{ "Resourcefulness", "Interface\\Icons\\Ability_Hunter_Resourcefulness", 4, 1},
														{ "Mirrored Blades", "INTERFACE\\ICONS\\inv_weapon_shortblade_99", 4, 2},
														{ "T.N.T.", "Interface\\Icons\\INV_Misc_Bomb_05", 4, 3},
														{ "Toxicology", "INTERFACE\\ICONS\\inv_alchemy_enchantedvial", 5, 1},
														{ "Wyvern Sting", "Interface\\Icons\\INV_Spear_02", 5, 2},
														{ "Noxious Stings", "Interface\\Icons\\Ability_Hunter_PotentVenom", 5, 3},
														{ "Hunting Party", "Interface\\Icons\\Ability_Hunter_HuntingParty", 5, 4},
														{ "Sniper Training", "Interface\\Icons\\Ability_Hunter_LongShots", 6, 1},
														{ "Serpent Spread", "Interface\\Icons\\Ability_Hunter_SerpentSwiftness", 6, 3},
														{ "Black Arrow", "Interface\\Icons\\Spell_Shadow_PainSpike", 7, 2},
													 }
							},
						 },
						 
["Mage"] = {
							{
								["name"] = "Arcane", 
								["data"] = {
														{ "Arcane Concentration", "Interface\\Icons\\Spell_Shadow_ManaBurn", 1, 1},
														{ "Improved Counterspell", "Interface\\Icons\\Spell_Frost_IceShock", 1, 2},
														{ "Netherwind Presence", "Interface\\Icons\\Ability_Mage_NetherWindPresence", 1, 3},
														{ "Torment the Weak", "Interface\\Icons\\Spell_Arcane_FocusedPower", 2, 1},
														{ "Invocation", "INTERFACE\\ICONS\\spell_arcane_invocation", 2, 2},
														{ "Improved Arcane Missiles", "Interface\\Icons\\Spell_Nature_StarFall", 2, 3},
														{ "Improved Blink", "Interface\\Icons\\Spell_Arcane_Blink", 2, 4},
														{ "Arcane Flows", "Interface\\Icons\\Ability_Mage_PotentSpirit", 3, 1},
														{ "Presence of Mind", "Interface\\Icons\\Spell_Nature_EnchantArmor", 3, 2},
														{ "Missile Barrage", "Interface\\Icons\\Ability_Mage_MissileBarrage", 3, 3},
														{ "Prismatic Cloak", "Interface\\Icons\\Spell_Arcane_PrismaticCloak", 3, 4},
														{ "Improved Polymorph", "Interface\\Icons\\Spell_Nature_Polymorph", 4, 1},
														{ "Arcane Tactics", "INTERFACE\\ICONS\\spell_arcane_arcanetactics", 4, 2},
														{ "Incanter's Absorption", "Interface\\Icons\\Ability_Mage_IncantersAbsorbtion", 4, 3},
														{ "test", "test", 1, 1},
														{ "Improved Arcane Explosion", "Interface\\Icons\\Spell_Nature_WispSplode", 4, 4},
														{ "Arcane Potency", "Interface\\Icons\\Spell_Arcane_ArcanePotency", 5, 1},
														{ "Slow", "Interface\\Icons\\Spell_Nature_Slow", 5, 2},
														{ "Nether Vortex", "Interface\\Icons\\Spell_Arcane_Blast", 5, 3},
														{ "Focus Magic", "Interface\\Icons\\Spell_Arcane_StudentOfMagic", 6, 1},
														{ "Improved Mana Gem", "Interface\\Icons\\INV_Misc_Gem_Emerald_01", 6, 3},
														{ "Arcane Power", "Interface\\Icons\\Spell_Nature_Lightning", 7, 2},
													 }
							},
							{
								["name"] = "Fire", 
								["data"] = {
														{ "Master of Elements", "Interface\\Icons\\Spell_Fire_MasterOfElements", 1, 1},
														{ "Burning Soul", "INTERFACE\\ICONS\\spell_burningsoul", 1, 2},
														{ "Improved Fire Blast", "Interface\\Icons\\Spell_Fire_Fireball", 1, 3},
														{ "Ignite", "Interface\\Icons\\Spell_Fire_Incinerate", 2, 1},
														{ "Fire Power", "Interface\\Icons\\Spell_Fire_Immolation", 2, 2},
														{ "Blazing Speed", "Interface\\Icons\\Spell_Fire_BurningSpeed", 2, 3},
														{ "Impact", "Interface\\Icons\\Spell_Fire_MeteorStorm", 2, 4},
														{ "Cauterize", "Interface\\Icons\\spell_fire_rune", 3, 1},
														{ "Blast Wave", "Interface\\Icons\\Spell_Holy_Excorcism_02", 3, 2},
														{ "Hot Streak", "Interface\\Icons\\Ability_Mage_HotStreak", 3, 3},
														{ "Improved Scorch", "Interface\\Icons\\Spell_Fire_SoulBurn", 3, 4},
														{ "Molten Shields", "Interface\\Icons\\Spell_Fire_FireArmor", 4, 1},
														{ "Combustion", "Interface\\Icons\\Spell_Fire_SealOfFire", 4, 2},
														{ "Improved Hot Streak", "Interface\\Icons\\Ability_Mage_HotStreak", 4, 3},
														{ "Firestarter", "Interface\\Icons\\Ability_Mage_FireStarter", 4, 4},
														{ "Improved Flamestrike", "Interface\\Icons\\Spell_Fire_SelfDestruct", 5, 1},
														{ "Dragon's Breath", "Interface\\Icons\\INV_Misc_Head_Dragon_01", 5, 2},
														{ "Molten Fury", "Interface\\Icons\\Spell_Fire_MoltenBlood", 5, 3},
														{ "Pyromaniac", "Interface\\Icons\\Spell_Fire_Burnout", 6, 1},
														{ "Critical Mass", "Interface\\Icons\\Spell_Nature_WispHeal", 6, 3},
														{ "Living Bomb", "Interface\\Icons\\Ability_Mage_LivingBomb", 7, 2},
													 }
							},
							{ 
								["name"] = "Frost", 
								["data"] = {
														{ "Early Frost", "Interface\\Icons\\Spell_Frost_ChillingBolt", 1, 1},
														{ "Piercing Ice", "Interface\\Icons\\Spell_Frost_Frostbolt", 1, 2},
														{ "Shatter", "Interface\\Icons\\Spell_Frost_FrostShock", 1, 3},
														{ "Ice Floes", "Interface\\Icons\\Spell_Frost_IceFloes", 2, 1},
														{ "Improved Cone of Cold", "Interface\\Icons\\Spell_Frost_Glacier", 2, 2},
														{ "Piercing Chill", "INTERFACE\\ICONS\\spell_frost_piercing chill", 2, 3},
														{ "Permafrost", "Interface\\Icons\\Spell_Frost_Wisp", 2, 4},
														{ "Ice Shards", "INTERFACE\\ICONS\\spell_frost_ice shards", 3, 1},
														{ "Icy Veins", "Interface\\Icons\\Spell_Frost_ColdHearted", 3, 2},
														{ "Fingers of Frost", "Interface\\Icons\\Ability_Mage_WintersGrasp", 3, 3},
														{ "Improved Freeze", "Interface\\Icons\\Spell_Frost_SummonWaterElemental", 3, 4},
														{ "Enduring Winter", "Interface\\Icons\\Spell_Frost_ArcticWinds", 4, 1},
														{ "Cold Snap", "Interface\\Icons\\Spell_Frost_WizardMark", 4, 2},
														{ "Brain Freeze", "Interface\\Icons\\Ability_Mage_BrainFreeze", 4, 3},
														{ "Shattered Barrier", "Interface\\Icons\\Ability_Mage_ColdAsIce", 5, 1},
														{ "Ice Barrier", "Interface\\Icons\\Spell_Ice_Lament", 5, 2},
														{ "Reactive Barrier", "Interface\\Icons\\Spell_Frost_ManaRecharge", 5, 3},
														{ "Frostfire Orb", "INTERFACE\\ICONS\\spell_firefrost orb", 6, 3},
														{ "Deep Freeze", "Interface\\Icons\\Ability_Mage_DeepFreeze", 7, 2},
													 }
							}
					},
					
["Death Knight"] = {
										{ 
											["name"] = "Blood", 
											["data"] = {
																	{ "Butchery", "Interface\\Icons\\INV_Axe_68", 1, 1},
																	{ "Blade Barrier", "Interface\\Icons\\Ability_UpgradeMoonGlaive", 1, 2},
																	{ "Bladed Armor", "Interface\\Icons\\INV_Shoulder_36", 1, 3},
																	{ "Improved Blood Tap", "Interface\\Icons\\Spell_DeathKnight_BloodTap", 2, 1},
																	{ "Scent of Blood", "Interface\\Icons\\Ability_Rogue_BloodyEye", 2, 2},
																	{ "Scarlet Fever", "INTERFACE\\ICONS\\ability_rogue_vendetta", 2, 3},
																	{ "Hand of Doom", "INTERFACE\\ICONS\\ability_deathknight_desolation", 2, 4},
																	{ "Blood-Caked Blade", "Interface\\Icons\\Ability_CriticalStrike", 3, 1},
																	{ "Bone Shield", "INTERFACE\\ICONS\\ability_deathknight_boneshield", 3, 2},
																	{ "Toughness", "Interface\\Icons\\Spell_Holy_Devotion", 3, 3},
																	{ "Abomination's Might", "Interface\\Icons\\Ability_Warrior_IntensifyRage", 3, 4},
																	{ "Sanguine Fortitude", "INTERFACE\\ICONS\\ability_deathknight_sanguinfortitude", 4, 1},
																	{ "Blood Parasite", "Interface\\Icons\\Spell_Shadow_SoulLeech", 4, 2},
																	{ "Improved Blood Presence", "Interface\\Icons\\Spell_Deathknight_BloodPresence", 4, 3},
																	{ "Will of the Necropolis", "Interface\\Icons\\Ability_Creature_Cursed_02", 5, 1},
																	{ "Rune Tap", "Interface\\Icons\\Spell_DeathKnight_RuneTap", 5, 2},
																	{ "Vampiric Blood", "Interface\\Icons\\Spell_Shadow_LifeDrain", 5, 3},
																	{ "Improved Death Strike", "Interface\\Icons\\Spell_DeathKnight_Butcher2", 6, 2},
																	{ "Crimson Scourge", "Interface\\Icons\\Spell_DeathKnight_BloodBoil", 6, 3},
																	{ "Dancing Rune Weapon", "Interface\\Icons\\INV_Sword_07", 7, 2},
																 }
										},
										{
											["name"] = "Frost", 
											["data"] = {
																	{ "Runic Power Mastery", "Interface\\Icons\\Spell_Arcane_Arcane01", 1, 1},
																	{ "Icy Reach", "Interface\\Icons\\Spell_Frost_ManaRecharge", 1, 2},
																	{ "Nerves of Cold Steel", "Interface\\Icons\\Ability_DualWield", 1, 3},
																	{ "Annihilation", "Interface\\Icons\\INV_Weapon_Hand_18", 2, 1},
																	{ "Lichborne", "Interface\\Icons\\Spell_Shadow_RaiseDead", 2, 2},
																	{ "On a Pale Horse", "Interface\\Icons\\Ability_Mount_Undeadhorse", 2, 3},
																	{ "Endless Winter", "Interface\\Icons\\Spell_Shadow_Twilight", 2, 4},
																	{ "Merciless Combat", "Interface\\Icons\\INV_Sword_112", 3, 1},
																	{ "Chill of the Grave", "Interface\\Icons\\Spell_Frost_FrostShock", 3, 2},
																	{ "Killing Machine", "Interface\\Icons\\INV_Sword_122", 3, 3},
																	{ "Rime", "Interface\\Icons\\Spell_Frost_FreezingBreath", 4, 1},
																	{ "Pillar of Frost", "INTERFACE\\ICONS\\ability_deathknight_pillaroffrost", 4, 2},
																	{ "Improved Icy Talons", "Interface\\Icons\\Spell_Deathknight_IcyTalons", 4, 3},
																	{ "Brittle Bones", "INTERFACE\\ICONS\\ability_deathknight_brittlebones", 4, 4},
																	{ "Chilblains", "Interface\\Icons\\Spell_Frost_Wisp", 5, 1},
																	{ "Hungering Cold", "Interface\\Icons\\INV_Staff_15", 5, 2},
																	{ "Improved Frost Presence", "Interface\\Icons\\Spell_Deathknight_FrostPresence", 5, 3},
																	{ "Threat of Thassarian", "Interface\\Icons\\Ability_DualWieldSpecialization", 6, 1},
																	{ "Might of the Frozen Wastes", "INTERFACE\\ICONS\\inv_sword_120", 6, 3},
																	{ "Howling Blast", "Interface\\Icons\\Spell_Frost_ArcticWinds", 7, 2},
																 }
										}
									},
										
["Warrior"] = {
								{
									["name"] = "Arms", 
									["data"] = {
															{ "War Academy", "Interface\\Icons\\Ability_Warrior_UnrelentingAssault", 1, 1},
															{ "Field Dressing", "Interface\\Icons\\INV_Misc_Bandage_05", 1, 2},
															{ "Blitz", "INTERFACE\\ICONS\\warrior_talent_icon_blitz", 1, 3},
															{ "Tactical Mastery", "Interface\\Icons\\Spell_Nature_EnchantArmor", 2, 1},
															{ "Second Wind", "Interface\\Icons\\Ability_Hunter_Harass", 2, 2},
															{ "Deep Wounds", "Interface\\Icons\\Ability_BackStab", 2, 3},
															{ "Drums of War", "Interface\\Icons\\Achievement_BG_winWSG_3-0", 2, 4},
															{ "Taste for Blood", "Interface\\Icons\\Ability_Rogue_HungerforBlood", 3, 1},
															{ "Sweeping Strikes", "Interface\\Icons\\Ability_Rogue_SliceDice", 3, 2},
															{ "Impale", "Interface\\Icons\\Ability_SearingArrow", 3, 3},
															{ "Improved Hamstring", "Interface\\Icons\\Ability_ShockWave", 3, 4},
															{ "Improved Slam", "Interface\\Icons\\Ability_Warrior_DecisiveStrike", 4, 1},
															{ "Deadly Calm", "INTERFACE\\ICONS\\achievement_boss_kingymiron", 4, 2},
															{ "Blood Frenzy", "Interface\\Icons\\Ability_Warrior_BloodFrenzy", 4, 3},
															{ "Lambs to the Slaughter", "INTERFACE\\ICONS\\warrior_talent_icon_lambstotheslaughter", 5, 1},
															{ "Juggernaut", "Interface\\Icons\\Ability_Warrior_BullRush", 5, 2},
															{ "Sudden Death", "Interface\\Icons\\Ability_Warrior_ImprovedDisciplines", 5, 4},
															{ "Wrecking Crew", "Interface\\Icons\\Ability_Warrior_Trauma", 6, 1},
															{ "Throwdown", "INTERFACE\\ICONS\\inv_mace_62", 6, 3},
															{ "Bladestorm", "Interface\\Icons\\Ability_Warrior_Bladestorm", 7, 2},
														 }
								},
								{
									["name"] = "Fury", 
									["data"] = {
															{ "Blood Craze", "Interface\\Icons\\Spell_Shadow_SummonImp", 1, 1},
															{ "Battle Trance", "Interface\\Icons\\INV_Helmet_06", 1, 2},
															{ "Cruelty", "Interface\\Icons\\Ability_Rogue_Eviscerate", 1, 3},
															{ "Executioner", "Interface\\Icons\\INV_Sword_48", 2, 1},
															{ "Booming Voice", "Interface\\Icons\\Spell_Nature_Purge", 2, 2},
															{ "Rude Interruption", "Interface\\Icons\\Ability_Warrior_CommandingShout", 2, 3},
															{ "Piercing Howl", "Interface\\Icons\\Spell_Shadow_DeathScream", 2, 4},
															{ "Flurry", "Interface\\Icons\\Ability_GhoulFrenzy", 3, 1},
															{ "Death Wish", "Interface\\Icons\\Spell_Shadow_DeathPact", 3, 2},
															{ "Enrage", "Interface\\Icons\\Spell_Shadow_UnholyFrenzy", 3, 3},
															{ "Die by the Sword", "INTERFACE\\ICONS\\inv_sword_86", 4, 1},
															{ "Raging Blow", "Interface\\Icons\\Ability_Hunter_SwiftStrike", 4, 2},
															{ "Rampage", "Interface\\Icons\\Ability_Warrior_Rampage", 4, 3},
															{ "Heroic Fury", "INTERFACE\\ICONS\\warrior_talent_icon_deadlycalm", 4, 4},
															{ "Furious Attacks", "Interface\\Icons\\Ability_Warrior_FuriousResolve", 5, 1},
															{ "Meat Cleaver", "INTERFACE\\ICONS\\warrior_talent_icon_mastercleaver", 5, 3},
															{ "Intensify Rage", "INTERFACE\\ICONS\\warrior_talent_icon_furyintheblood", 5, 4},
															{ "Bloodsurge", "Interface\\Icons\\Ability_Warrior_Bloodsurge", 6, 2},
															{ "Skirmisher", "INTERFACE\\ICONS\\warrior_talent_icon_skirmisher", 6, 3},
															{ "Titan's Grip", "Interface\\Icons\\Ability_Warrior_TitansGrip", 7, 2},
															{ "Single-Minded Fury", "INTERFACE\\ICONS\\warrior_talent_icon_singlemindedfury", 7, 3},
														 }
								},
								{ 
									["name"] = "Protection", 
									["data"] = {
															{ "Incite", "Interface\\Icons\\Ability_Warrior_Incite", 1, 1},
															{ "Toughness", "Interface\\Icons\\Spell_Holy_Devotion", 1, 2},
															{ "Blood and Thunder", "INTERFACE\\ICONS\\warrior_talent_icon_bloodandthunder", 1, 3},
															{ "Shield Specialization", "Interface\\Icons\\INV_Shield_06", 2, 1},
															{ "Shield Mastery", "Interface\\Icons\\Ability_Warrior_ShieldGuard", 2, 2},
															{ "Hold the Line", "Interface\\Icons\\Achievement_BG_DefendXtowers_AV", 2, 3},
															{ "Gag Order", "Interface\\Icons\\INV_Axe_66", 2, 4},
															{ "Last Stand", "Interface\\Icons\\Spell_Holy_AshesToAshes", 3, 1},
															{ "Concussion Blow", "Interface\\Icons\\Ability_ThunderBolt", 3, 2},
															{ "Bastion of Defense", "Interface\\Icons\\Ability_Defend", 3, 3},
															{ "Warbringer", "Interface\\Icons\\Ability_Warrior_Warbringer", 3, 4},
															{ "Improved Revenge", "Interface\\Icons\\Ability_Warrior_Revenge", 4, 1},
															{ "Devastate", "Interface\\Icons\\INV_Sword_11", 4, 3},
															{ "Impending Victory", "Interface\\Icons\\Ability_Warrior_Devastate", 4, 4},
															{ "Thunderstruck", "INTERFACE\\ICONS\\warrior_talent_icon_thunderstruck", 5, 1},
															{ "Vigilance", "Interface\\Icons\\Ability_Warrior_Vigilance", 5, 2},
															{ "Heavy Repercussions", "Interface\\Icons\\INV_Shield_01", 5, 4},
															{ "Safeguard", "Interface\\Icons\\Ability_Warrior_Safeguard", 6, 2},
															{ "Sword and Board", "Interface\\Icons\\Ability_Warrior_SwordandBoard", 6, 3},
															{ "Shockwave", "Interface\\Icons\\Ability_Warrior_Shockwave", 7, 2},
														}
								}
				},
["Shaman"] = {
								{ 
								["name"] = "Elemental", 
								["data"] = {
															{ "Acuity", "Interface\\Icons\\Spell_Nature_AstralRecalGroup", 1, 1},
															{ "Convection", "INTERFACE\\ICONS\\spell_shaman_convection", 1, 2},
															{ "Concussion", "Interface\\Icons\\Spell_Fire_Fireball", 1, 3},
															{ "Call of Flame", "Interface\\Icons\\Spell_Fire_Immolation", 2, 1},
															{ "Elemental Warding", "Interface\\Icons\\Spell_Nature_SpiritArmor", 2, 2},
															{ "Reverberation", "Interface\\Icons\\Spell_Frost_FrostWard", 2, 3},
															{ "Elemental Precision", "Interface\\Icons\\Spell_Nature_ElementalPrecision_1", 2, 4},
															{ "Rolling Thunder", "Interface\\Icons\\Spell_Nature_CallStorm", 3, 1},
															{ "Elemental Focus", "Interface\\Icons\\Spell_Shadow_ManaBurn", 3, 2},
															{ "Elemental Reach", "Interface\\Icons\\Spell_Nature_StormReach", 3, 3},
															{ "Elemental Oath", "Interface\\Icons\\Spell_Shaman_ElementalOath", 4, 2},
															{ "Lava Flows", "Interface\\Icons\\Spell_Shaman_LavaFlow", 4, 3},
															{ "Fulmination", "Interface\\Icons\\Spell_Nature_UnrelentingStorm", 5, 1},
															{ "Elemental Mastery", "Interface\\Icons\\Spell_Nature_WispHeal", 5, 2},
															{ "Earth's Grasp", "Interface\\Icons\\Spell_Nature_StrangleVines", 5, 3},
															{ "Totemic Wrath", "Interface\\Icons\\Spell_Fire_TotemOfWrath", 5, 4},
															{ "Feedback", "INTERFACE\\ICONS\\ability_vehicle_electrocharge", 6, 2},
															{ "Lava Surge", "INTERFACE\\ICONS\\spell_shaman_lavasurge", 6, 3},
															{ "Earthquake", "INTERFACE\\ICONS\\spell_shaman_earthquake", 7, 2},
														}
									},
									{
										["name"] = "Enhancement", 
										["data"] = {
																{ "Elemental Weapons", "Interface\\Icons\\Spell_Fire_FlameTounge", 1, 1},
																{ "Focused Strikes", "INTERFACE\\ICONS\\spell_shaman_focusedstrikes", 1, 2},
																{ "Improved Shields", "Interface\\Icons\\Spell_Nature_LightningShield", 1, 3},
																{ "Elemental Devastation", "Interface\\Icons\\Spell_Fire_ElementalDevastation", 2, 1},
																{ "Flurry", "Interface\\Icons\\Ability_GhoulFrenzy", 2, 2},
																{ "Ancestral Swiftness", "INTERFACE\\ICONS\\spell_lifegivingspeed", 2, 3},
																{ "Totemic Reach", "Interface\\Icons\\Spell_Nature_AgitatingTotem", 2, 4},
																{ "Toughness", "Interface\\Icons\\Spell_Holy_Devotion", 3, 1},
																{ "Stormstrike", "Interface\\Icons\\Ability_Shaman_Stormstrike", 3, 2},
																{ "Static Shock", "Interface\\Icons\\Spell_Shaman_StaticShock", 3, 3},
																{ "Frozen Power", "Interface\\Icons\\Spell_Fire_BlueCano", 4, 1},
																{ "Seasoned Winds", "Interface\\Icons\\Spell_Nature_ElementalAbsorption", 4, 2},
																{ "Searing Flames", "Interface\\Icons\\Spell_Fire_SearingTotem", 4, 3},
																{ "Earthen Power", "Interface\\Icons\\Spell_Nature_EarthElemental_Totem", 5, 1},
																{ "Shamanistic Rage", "Interface\\Icons\\Spell_Nature_ShamanRage", 5, 2},
																{ "Unleashed Rage", "Interface\\Icons\\Spell_Nature_UnleashedRage", 5, 4},
																{ "Maelstrom Weapon", "Interface\\Icons\\Spell_Shaman_MaelstromWeapon", 6, 2},
																{ "Improved Lava Lash", "INTERFACE\\ICONS\\spell_shaman_improvelavalash", 6, 3},
																{ "Feral Spirit", "Interface\\Icons\\Spell_Shaman_FeralSpirit", 7, 2},
															 }
									},
									{ 
										["name"] = "Restoration", 
										["data"] = {
																{ "Ancestral Resolve", "Interface\\Icons\\spell_nature_rune", 1, 1},
																{ "Tidal Focus", "Interface\\Icons\\Spell_Frost_ManaRecharge", 1, 2},
																{ "Spark of Life", "Interface\\Icons\\Spell_Nature_WispSplodeGreen", 1, 3},
																{ "Improved Water Shield", "Interface\\Icons\\Ability_Shaman_WaterShield", 2, 1},
																{ "Totemic Focus", "Interface\\Icons\\Spell_Nature_MoonGlow", 2, 2},
																{ "Focused Insight", "INTERFACE\\ICONS\\spell_shaman_measuredinsight", 2, 3},
																{ "Nature's Guardian", "Interface\\Icons\\Spell_Nature_NatureGuardian", 2, 4},
																{ "Ancestral Healing", "Interface\\Icons\\Spell_Nature_UndyingStrength", 3, 1},
																{ "Nature's Swiftness", "Interface\\Icons\\Spell_Nature_RavenForm", 3, 2},
																{ "Nature's Blessing", "Interface\\Icons\\Spell_Nature_NatureBlessing", 3, 3},
																{ "Soothing Rains", "Interface\\Icons\\Spell_Nature_GiftoftheWaterSpirit", 4, 2},
																{ "Improved Cleanse Spirit", "Interface\\Icons\\Ability_Shaman_CleanseSpirit", 4, 3},
																{ "Cleansing Waters", "Interface\\Icons\\Spell_Nature_Regeneration_02", 4, 4},
																{ "Ancestral Awakening", "Interface\\Icons\\Spell_Shaman_AncestralAwakening", 5, 1},
																{ "Mana Tide Totem", "Interface\\Icons\\Spell_Frost_SummonWaterElemental", 5, 2},
																{ "Telluric Currents", "Interface\\Icons\\Spell_Lightning_LightningBolt01", 5, 3},
																{ "Spirit Link Totem", "Interface\\Icons\\Spell_Shaman_SpiritLink", 5, 4},
																{ "Tidal Waves", "Interface\\Icons\\Spell_Shaman_TidalWaves", 6, 2},
																{ "Blessing of the Eternals", "Interface\\Icons\\Spell_Shaman_BlessingOfEternals", 6, 3},
																{ "Riptide", "Interface\\Icons\\spell_nature_riptide", 7, 2},
															 }
									}
						},
["Paladin"] = {
								{ 
									["name"] = "Holy", 
									["data"] = {
															{ "Arbiter of the Light", "Interface\\Icons\\Spell_Holy_HealingAura", 1, 1},
															{ "Protector of the Innocent", "INTERFACE\\ICONS\\ability_paladin_protectoroftheinnocent", 1, 2},
															{ "Judgements of the Pure", "Interface\\Icons\\Ability_Paladin_JudgementofthePure", 1, 3},
															{ "Clarity of Purpose", "INTERFACE\\ICONS\\spell_paladin_clarityofpurpose", 2, 1},
															{ "Last Word", "Interface\\Icons\\Spell_Holy_HolyGuidance", 2, 2},
															{ "Blazing Light", "Interface\\Icons\\Spell_Holy_HolyBolt", 2, 3},
															{ "Denounce", "Interface\\Icons\\Spell_Holy_Excorcism_02", 3, 1},
															{ "Divine Favor", "Interface\\Icons\\Spell_Holy_DivineIllumination", 3, 2},
															{ "Infusion of Light", "Interface\\Icons\\Ability_Paladin_InfusionofLight", 3, 3},
															{ "Daybreak", "Interface\\Icons\\INV_QirajIdol_Sun", 3, 4},
															{ "Enlightened Judgements", "Interface\\Icons\\Ability_Paladin_EnlightenedJudgements", 4, 1},
															{ "Beacon of Light", "Interface\\Icons\\Ability_Paladin_BeaconofLight", 4, 2},
															{ "Speed of Light", "INTERFACE\\ICONS\\paladin_icon_speedoflight", 4, 3},
															{ "Sacred Cleansing", "Interface\\Icons\\Ability_Paladin_SacredCleansing", 4, 4},
															{ "Conviction", "INTERFACE\\ICONS\\ability_paladin_conviction", 5, 1},
															{ "Aura Mastery", "Interface\\Icons\\Spell_Holy_AuraMastery", 5, 3},
															{ "Paragon of Virtue", "Interface\\Icons\\Spell_Holy_AvengineWrath", 5, 4},
															{ "Tower of Radiance", "Interface\\Icons\\Achievement_BG_winSOA", 6, 2},
															{ "Blessed Life", "Interface\\Icons\\Spell_Holy_BlessedLife", 6, 3},
															{ "Light of Dawn", "INTERFACE\\ICONS\\spell_paladin_lightofdawn", 7, 2},
														 }
								},
								{ 
									["name"] = "Protection", 
									["data"] = {
															{ "Divinity", "Interface\\Icons\\Spell_Holy_BlindingHeal", 1, 1},
															{ "Seals of the Pure", "Interface\\Icons\\INV_Mace_46", 1, 2},
															{ "Eternal Glory", "Interface\\Icons\\INV_Torch_Thrown", 1, 3},
															{ "Judgements of the Just", "Interface\\Icons\\Ability_Paladin_JudgementsoftheJust", 2, 1},
															{ "Toughness", "Interface\\Icons\\Spell_Holy_Devotion", 2, 2},
															{ "Improved Hammer of Justice", "Interface\\Icons\\Spell_Holy_SealOfMight", 2, 3},
															{ "Hallowed Ground", "Interface\\Icons\\Spell_Holy_InnerFire", 3, 1},
															{ "Sanctuary", "Interface\\Icons\\Spell_Nature_LightningShield", 3, 2},
															{ "Hammer of the Righteous", "Interface\\Icons\\Ability_Paladin_HammeroftheRighteous", 3, 3},
															{ "Wrath of the Lightbringer", "INTERFACE\\ICONS\\inv_mace_82", 3, 4},
															{ "Reckoning", "Interface\\Icons\\Spell_Holy_BlessingOfStrength", 4, 1},
															{ "Shield of the Righteous", "Interface\\Icons\\Ability_Paladin_ShieldofVengeance", 4, 2},
															{ "Grand Crusader", "Interface\\Icons\\INV_Helmet_74", 4, 3},
															{ "Vindication", "Interface\\Icons\\Spell_Holy_Vindication", 5, 1},
															{ "Holy Shield", "Interface\\Icons\\Spell_Holy_BlessingOfProtection", 5, 2},
															{ "Guarded by the Light", "Interface\\Icons\\Ability_Paladin_GaurdedbytheLight", 5, 3},
															{ "Divine Guardian", "Interface\\Icons\\spell_holy_powerwordbarrier", 5, 4},
															{ "Sacred Duty", "Interface\\Icons\\Spell_Holy_DivineIntervention", 6, 2},
															{ "Shield of the Templar", "Interface\\Icons\\Ability_Paladin_ShieldoftheTemplar", 6, 3},
															{ "Ardent Defender", "Interface\\Icons\\Spell_Holy_ArdentDefender", 7, 2},
														 }
								},
								{
									["name"] = "Retribution", 
									["data"] = {
															{ "Eye for an Eye", "Interface\\Icons\\Spell_Holy_EyeforanEye", 1, 1},
															{ "Crusade", "Interface\\Icons\\Spell_Holy_Crusade", 1, 2},
															{ "Improved Judgement", "Interface\\Icons\\Ability_Paladin_JudgementBlue", 1, 3},
															{ "Guardian's Favor", "Interface\\Icons\\Spell_Holy_SealOfProtection", 2, 1},
															{ "Rule of Law", "Interface\\Icons\\INV_Relics_LibramofHope", 2, 2},
															{ "Pursuit of Justice", "Interface\\Icons\\Spell_Holy_PersuitofJustice", 2, 4},
															{ "Communion", "Interface\\Icons\\Ability_Paladin_JudgementoftheWise", 3, 1},
															{ "The Art of War", "Interface\\Icons\\Ability_Paladin_ArtofWar", 3, 2},
															{ "Long Arm of the Law", "Interface\\Icons\\Ability_Paladin_JudgementRed", 3, 3},
															{ "Divine Storm", "Interface\\Icons\\Ability_Paladin_DivineStorm", 3, 4},
															{ "Sacred Shield", "Interface\\Icons\\Ability_Paladin_BlessedMending", 4, 1},
															{ "Sanctity of Battle", "INTERFACE\\ICONS\\inv_sword_136", 4, 2},
															{ "Seals of Command", "Interface\\Icons\\Ability_Warrior_InnerRage", 4, 3},
															{ "Sanctified Wrath", "Interface\\Icons\\Ability_Paladin_SanctifiedWrath", 4, 4},
															{ "Selfless Healer", "Interface\\Icons\\spell_holy_rune", 5, 1},
															{ "Repentance", "Interface\\Icons\\Spell_Holy_PrayerOfHealing", 5, 2},
															{ "Divine Purpose", "Interface\\Icons\\Spell_Holy_DivinePurpose", 5, 3},
															{ "Inquiry of Faith", "Interface\\Icons\\Ability_Paladin_RighteousVengeance", 6, 2},
															{ "Acts of Sacrifice", "Interface\\Icons\\Ability_Paladin_BlessedHands", 6, 3},
															{ "Zealotry", "Interface\\Icons\\Spell_Holy_ProclaimChampion_02", 7, 2},
														 }
								},
					},
						
["Priest"] = {
								{ 
									["name"] = "Discipline", 
									["data"] = {
															{ "Improved Power Word: Shield", "Interface\\Icons\\Spell_Holy_PowerWordShield", 1, 1},
															{ "Twin Disciplines", "Interface\\Icons\\Spell_Holy_SealOfVengeance", 1, 2},
															{ "Mental Agility", "Interface\\Icons\\Ability_Hibernation", 1, 3},
															{ "Evangelism", "Interface\\Icons\\Spell_Holy_DivineIllumination", 2, 1},
															{ "Archangel", "INTERFACE\\ICONS\\ability_priest_archangel", 2, 2},
															{ "Inner Sanctum", "Interface\\Icons\\Spell_Holy_InnerFire", 2, 3},
															{ "Soul Warding", "INTERFACE\\ICONS\\ability_priest_soulwarding", 2, 4},
															{ "Renewed Hope", "Interface\\Icons\\Spell_Holy_HolyProtection", 3, 1},
															{ "Power Infusion", "Interface\\Icons\\Spell_Holy_PowerInfusion", 3, 2},
															{ "Atonement", "INTERFACE\\ICONS\\ability_priest_atonement", 3, 3},
															{ "Inner Focus", "Interface\\Icons\\Spell_Frost_WindWalkOn", 3, 4},
															{ "Rapture", "Interface\\Icons\\Spell_Holy_Rapture", 4, 2},
															{ "Borrowed Time", "Interface\\Icons\\Spell_Holy_BorrowedTime", 4, 3},
															{ "Reflective Shield", "INTERFACE\\ICONS\\ability_priest_reflectiveshield", 4, 4},
															{ "Strength of Soul", "Interface\\Icons\\Spell_Holy_AshesToAshes", 5, 1},
															{ "Divine Aegis", "Interface\\Icons\\Spell_Holy_DevineAegis", 5, 2},
															{ "Pain Suppression", "Interface\\Icons\\Spell_Holy_PainSupression", 5, 3},
															{ "Train of Thought", "Interface\\Icons\\Ability_Mage_StudentOfTheMind", 5, 4},
															{ "Focused Will", "INTERFACE\\ICONS\\ability_priest_focusedwill", 6, 1},
															{ "Grace", "Interface\\Icons\\Spell_Holy_HopeAndGrace", 6, 3},
															{ "Power Word: Barrier", "Interface\\Icons\\spell_holy_powerwordbarrier", 7, 2},
														 }
								},
								{ 
									["name"] = "Holy", 
									["data"] = {
															{ "Improved Renew", "Interface\\Icons\\Spell_Holy_Renew", 1, 1},
															{ "Empowered Healing", "Interface\\Icons\\Spell_Holy_GreaterHeal", 1, 2},
															{ "Divine Fury", "Interface\\Icons\\Spell_Holy_SealOfWrath", 1, 3},
															{ "Desperate Prayer", "Interface\\Icons\\Spell_Holy_Restoration", 2, 2},
															{ "Surge of Light", "Interface\\Icons\\Spell_Holy_SurgeOfLight", 2, 3},
															{ "Inspiration", "Interface\\Icons\\Spell_Holy_LayOnHands", 2, 4},
															{ "Divine Touch", "Interface\\Icons\\Ability_Paladin_InfusionofLight", 3, 1},
															{ "Holy Concentration", "Interface\\Icons\\Spell_Holy_Fanaticism", 3, 2},
															{ "Lightwell", "Interface\\Icons\\Spell_Holy_SummonLightwell", 3, 3},
															{ "Tome of Light", "Interface\\Icons\\INV_Misc_Book_07", 3, 4},
															{ "Rapid Renewal", "Interface\\Icons\\Ability_Paladin_BlessedMending", 4, 1},
															{ "Spirit of Redemption", "Interface\\Icons\\INV_Enchant_EssenceEternalLarge", 4, 3},
															{ "Serendipity", "Interface\\Icons\\Spell_Holy_Serendipity", 4, 4},
															{ "Body and Soul", "Interface\\Icons\\Spell_Holy_SymbolOfHope", 5, 1},
															{ "Chakra", "INTERFACE\\ICONS\\priest_icon_chakra", 5, 2},
															{ "Revelations", "INTERFACE\\ICONS\\ability_priest_bindingprayers", 5, 3},
															{ "Blessed Resilience", "Interface\\Icons\\Spell_Holy_BlessedResillience", 5, 4},
															{ "Test of Faith", "Interface\\Icons\\Spell_Holy_TestOfFaith", 6, 1},
															{ "State of Mind", "Interface\\Icons\\Spell_Arcane_MindMastery", 6, 2},
															{ "Circle of Healing", "Interface\\Icons\\Spell_Holy_CircleOfRenewal", 6, 3},
															{ "Guardian Spirit", "Interface\\Icons\\Spell_Holy_GuardianSpirit", 7, 2},
														 }
							}
				},
}
				